apiVersion: apps/v1
kind: Deployment
metadata:
  name: medpulse-backend
  labels:
    app: medpulse-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medpulse-backend
  template:
    metadata:
      labels:
        app: medpulse-backend
    spec:
      containers:
        - name: backend
          image: harbor.local.registry/medpulse/medpulse-backend
          ports:
            - containerPort: 3001
      imagePullSecrets:
        - name: harbor-secret
      
