apiVersion: apps/v1
kind: Deployment
metadata:
  name: medpulse-frontend
  labels:
    app: medpulse-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medpulse-frontend
  template:
    metadata:
      labels:
        app: medpulse-frontend
    spec:
      containers:
        - name: frontend
          image: harbor.local.registry/medpulse/medpulse-frontend:latest
          ports:
            - containerPort: 5173
      imagePullSecrets:
        - name: harbor-secret
