apiVersion: v1
kind: Service
metadata:
  name: medpulse-mongo-service
spec:
  selector:
    app: medpulse-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
