apiVersion: apps/v1
kind: Deployment
metadata:
  name: medpulse-mongo
  labels:
    app: medpulse-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medpulse-mongo
  template:
    metadata:
      labels:
        app: medpulse-mongo
    spec:
      containers:
        - name: mongo
          image: harbor.local.registry/medpulse/mongo:4.4
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}
      imagePullSecrets:
        - name: harbor-secret
