---
- name: Update apt package
  ansible.builtin.apt:
    update_cache: yes

- name: Install docker & docker compose
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
    state: present

- name: Ensure docker service is enable
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true